const COMMENT_INPUT_ACTION_TYPES = {
	SET_COMMENT: "SET_COMMENT",
	SET_IS_PROCESSING: "SET_IS_PROCESSING",
	SENT_COMMENT: "SENT_COMMENT",
	SET_LOADING: "SET_LOADING",
};

export default COMMENT_INPUT_ACTION_TYPES;
