const ACTION_TYPES = {
	SET_LOADING: "SET_LOADING",
	FIRST_RENDER: "FIRST_RENDER",
	SET_MAKE_CHANGES: "SET_MAKE_CHANGES",
	UPDATE_GROUP_IMAGE: "UPDATE_GROUP_IMAGE",
	UPDATE_GROUP_COVER_IMAGE: "UPDATE_GROUP_COVER_IMAGE",
	TOGGLE_IS_NAME_EDIT: "TOGGLE_IS_NAME_EDIT",
	TOGGLE_IS_BIO_EDIT: "TOGGLE_IS_BIO_EDIT",
	SET_GROUP_NAME: "SET_GROUP_NAME",
	SET_GROUP_BIO: "SET_GROUP_BIO",
};

export default ACTION_TYPES;
