const ACTION_TYPES = {
	SET_LOADING: "SET_LOADING",
	UPLOAD_IMAGE: "UPLOAD_IMAGE",
	REMOVE_IMAGE: "REMOVE_IMAGE",
	SET_TITLE: "SET_TITLE",
	SET_DESCRIPTION: "SET_DESCRIPTION",
};

export default ACTION_TYPES;
