const ACTION_TYPES = {
	SET_LOADING: "SET_LOADING",
	SET_NAME: "SET_NAME",
	SET_BIO: "SET_BIO",
	UPLOAD_IMAGE: "UPLOAD_IMAGE",
	REMOVE_IMAGE: "REMOVE_IMAGE",
	UPLOAD_COVER_IMAGE: "UPLOAD_COVER_IMAGE",
	REMOVE_COVER_IMAGE: "REMOVE_COVER_IMAGE",
};

export default ACTION_TYPES;
