const ACTION_TYPES = {
	SET_POST_DESCRIPTION: "SET_POST_DESCRIPTION",
	SET_HAS_IMAGE_PATH_CHANGED: "SET_HAS_IMAGE_PATH_CHANGED",
	SET_LOADING: "SET_LOADING",
	FIRST_RENDER: "FIRST_RENDER",
	REMOVE_IMAGE: "REMOVE_IMAGE",
	UPLOAD_IMAGE: "UPLOAD_IMAGE",
};

export default ACTION_TYPES;
