const ACTION_TYPES = {
	SET_LOADING: "SET_LOADING",
	FIRST_RENDER: "FIRST_RENDER",
	SET_SERVICE_NAME: "SET_SERVICE_NAME",
	SET_SERVICE_DESCRIPTION: "SET_SERVICE_DESCRIPTION",
	SET_SERVICE_CATEGORY: "SET_SERVICE_CATEGORY",
	SET_CONTACT_NUMBER: "SET_CONTACT_NUMBER",
	UPLOAD_IMAGE: "UPLOAD_IMAGE",
};

export default ACTION_TYPES;
