const ACTION_TYPES = {
	SET_LOADING: "SET_LOADING",
	SET_IS_PENDING: "SET_IS_PENDING",
	SET_FRIEND_STATUS: "SET_FRIEND_STATUS",
	SET_FRIEND_REQUEST: "SET_FRIEND_REQUEST",
};

export default ACTION_TYPES;
