const ACTION_TYPES = {
	SET_LOADING: "SET_LOADING",
	FIRST_RENDER: "FIRST_RENDER",
	SET_PRODUCT_NAME: "SET_PRODUCT_NAME",
	SET_PRODUCT_DESCRIPTION: "SET_PRODUCT_DESCRIPTION",
	SET_PRODUCT_PRICE: "SET_PRODUCT_PRICE",
	SET_PRODUCT_QUANTITY: "SET_PRODUCT_QUANTITY",
	SET_CONTACT_NUMBER: "SET_CONTACT_NUMBER",
	UPLOAD_IMAGE: "UPLOAD_IMAGE",
};

export default ACTION_TYPES;
