const ACTION_TYPES = {
	SET_LOADING: "SET_LOADING",
	SET_TEXT: "SET_TEXT",
	UPLOAD_IMAGE: "UPLOAD_IMAGE",
	UPLOAD_FILE: "UPLOAD_FILE",
	REMOVE_IMAGE: "REMOVE_IMAGE",
	REMOVE_FILE: "REMOVE_FILE",
	SET_INPUT_TYPE: "SET_INPUT_TYPE",
};

export default ACTION_TYPES;
