const ACTION_TYPES = {
	SET_COMMENT_DESCRIPTION: "SET_COMMENT_DESCRIPTION",
	TOGGLE_SHOW_OPTIONS: "TOGGLE_SHOW_OPTIONS",
	TOGGLE_EDIT_COMMENT_FORM: "TOGGLE_EDIT_COMMENT_FORM",
	SET_LOADING: "SET_LOADING",
};

export default ACTION_TYPES;
