const ACTION_TYPES = {
	SET_POST_DESCRIPTION: "SET_POST_DESCRIPTION",
	SET_HAS_POST_DESCRIPTION_CHANGED: "SET_HAS_POST_DESCRIPTION_CHANGED",
	SET_LOADING: "SET_LOADING",
	REMOVE_IMAGE: "REMOVE_IMAGE",
	REMOVE_FILE: "REMOVE_FILE",
	FIRST_RENDER: "FIRST_RENDER",
	UPLOAD_IMAGE: "UPLOAD_IMAGE",
	UPLOAD_FILE: "UPLOAD_FILE",
	SET_INPUT_TYPE: "SET_INPUT_TYPE",
};

export default ACTION_TYPES;
