const ACTION_TYPES = {
	FIRST_RENDER: "FIRST_RENDER",
	SET_LOADING: "SET_LOADING",
	SET_JOIN_GROUP_REQUEST_AND_STATUS: "SET_JOIN_GROUP_REQUEST_AND_STATUS",
	SET_LOAD_JOIN_GROUP_STATUS: "SET_LOAD_JOIN_GROUP_STATUS",
	SET_NUMBER_JOIN_GROUP_REQUESTS: "SET_NUMBER_JOIN_GROUP_REQUESTS",
	TOGGLE_SHOW_REPORT_FORM: "TOGGLE_SHOW_REPORT_FORM",
};

export default ACTION_TYPES;
