const ACTION_TYPES = {
	SET_LOADING: "SET_LOADING",
	SET_IS_LIKED: "SET_IS_LIKED",
	LIKE_POST: "LIKE_POST",
	DISLIKE_POST: "DISLIKE_POST",
	FIRST_RENDER: "FIRST_RENDER",
	SET_PROCESSING: "SET_PROCESSING",
	TOGGLE_COMMENT: "TOGGLE_COMMENT",
	TOGGLE_SHOW_OPTION_DIV: "TOGGLE_SHOW_OPTION_DIV",
	TOGGLE_SHOW_EDIT_POST_FORM: "TOGGLE_SHOW_EDIT_POST_FORM",
};

export default ACTION_TYPES;
