const ACTION_TYPES = {
	SET_LOADING: "SET_LOADING",
	SET_LOAD_MORE: "SET_LOAD_MORE",
	TOGGLE_SHOW_ADD_NEW_POST_FORM: "TOGGLE_SHOW_ADD_NEW_POST_FORM",
	INCREASE_COUNT: "INCREASE_COUNT",
};

export default ACTION_TYPES;
