const ACTION_TYPES = {
	SET_NAME: "SET_NAME",
	SET_DESCRIPTION: "SET_DESCRIPTION",
	SET_MADE_CHANGES: "SET_MADE_CHANGES",
	SET_CONTACT_NUMBER: "SET_CONTACT_NUMBER",
	ADD_CONTACT_NUMBER: "ADD_CONTACT_NUMBER",
	REMOVE_CONTACT_NUMBER: "REMOVE_CONTACT_NUMBER",
	SET_START_DATE: "SET_START_DATE",
	SET_END_DATE: "SET_END_DATE",
	SET_MIN_END_DATE: "SET_MIN_END_DATE",
	SET_VENUE: "SET_VENUE",
	UPLOAD_IMAGE: "UPLOAD_IMAGE",
	TOGGLE_IS_ONE_DAY_EVENT: "TOGGLE_IS_ONE_DAY_EVENT",
	SET_ONE_DATE: "SET_ONE_DATE",
	SET_START_TIME: "SET_START_TIME",
	SET_END_TIME: "SET_END_TIME",
	INCREASE_COUNT: "INCREASE_COUNT",
	DECREASE_COUNT: "DECREASE_COUNT",
	SET_ORGANIZER: "SET_ORGANIZER",
	RESET_STATE: "RESET_STATE",
};

export default ACTION_TYPES;
