const ACTION_TYPES = {
	SET_NAME: "SET_NAME",
	SET_CONTACT_NUMBER: "SET_CONTACT_NUMBER",
	SET_DESCRIPTION: "SET_DESCRIPTION",
	SET_MADE_CHANGES: "SET_MADE_CHANGES",
	SET_CATEGORY: "SET_CATEGORY",
	UPLOAD_IMAGE: "UPLOAD_IMAGE",
	REMOVE_IMAGE: "REMOVE_IMAGE",
	RESET_STATE: "RESET_STATE",
};

export default ACTION_TYPES;
