const ACTION_TYPES = {
	SET_NAME: "SET_NAME",
	SET_DESCRIPTION: "SET_DESCRIPTION",
	UPLOAD_IMAGE: "UPLOAD_IMAGE",
	REMOVE_IMAGE: "REMOVE_IMAGE",
	SET_PRICE: "SET_PRICE",
	SET_MADE_CHANGES: "SET_MADE_CHANGES",
	RESET_STATE: "RESET_STATE",
	SET_QUANTITY: "SET_QUANTITY",
	SET_CONTACT_NUMBER: "SET_CONTACT_NUMBER",
};

export default ACTION_TYPES;
