const ACTION_TYPES = {
	SET_LOADING: "SET_LOADING",
	SET_COMMENTS_ARRAY: "SET_COMMENTS_ARRAY",
	SET_HAS_COMMENT: "SET_HAS_COMMENT",
	HAS_COMMENT: "HAS_COMMENT",
	NO_COMMENT: "NO_COMMENT",
	ADD_NEW_COMMENT: "ADD_NEW_COMMENT",
};

export default ACTION_TYPES;
