const ACTION_TYPES = {
	FIRST_RENDER: "FIRST_RENDER",
	SET_LOADING: "SET_LOADING",
	SET_NAME: "SET_NAME",
	SET_GENDER: "SET_GENDER",
	SET_PHONE_NUMBER: "SET_PHONE_NUMBER",
};

export default ACTION_TYPES;
