const ACTION_TYPES = {
	SET_POST_DESCRIPTION: "SET_POST_DESCRIPTION",
	SET_HAS_POST_DESCRIPTION_CHANGED: "SET_HAS_POST_DESCRIPTION_CHANGED",
	SET_HAS_IMAGE_PATH_CHANGED: "SET_HAS_IMAGE_PATH_CHANGED",
	SET_IMAGE: "SET_IMAGE",
	SET_POST_IMAGE_PATH: "SET_POST_IMAGE_PATH",
	SET_LOADING: "SET_LOADING",
	FIRST_RENDER: "FIRST_RENDER",
	REMOVE_IMAGE: "REMOVE_IMAGE",
};

export default ACTION_TYPES;
