const ACTION_TYPES = {
	SET_IS_LIKED: "SET_IS_LIKED",
	LIKE_POST: "LIKE_POST",
	FIRST_RENDER: "FIRST_RENDER",
	DISLIKE_POST: "DISLIKE_POST",
	SET_PROCESSING: "SET_PROCESSING",
	TOGGLE_COMMENT: "TOGGLE_COMMENT",
	INCREASE_COMMENTS_COUNT: "INCREASE_COMMENTS_COUNT",
	DECREASE_COMMENTS_COUNT: "DECREASE_COMMENTS_COUNT",
	SET_POST_DESCRIPTION: "SET_POST_DESCRIPTION",
	SET_PROFILE_IMAGE_PATH: "SET_PROFILE_IMAGE_PATH",
	SET_COMMENTS_COUNT: "SET_COMMENTS_COUNT",
};

export default ACTION_TYPES;
