export const ACTION_TYPES = {
	FIEST_RENDER: "FIEST_RENDER",
	SET_PROFILE_IMAGE_PATH: "SET_PROFILE_IMAGE_PATH",
	SET_COVER_IMAGE_PATH: "SET_COVER_IMAGE_PATH",
	SET_NAME: "SET_NAME",
	SET_BIO: "SET_BIO",
	SET_LOADING: "SET_LOADING",
	TOGGLE_IS_NAME_EDIT: "TOGGLE_IS_NAME_EDIT",
	TOGGLE_IS_BIO_EDIT: "TOGGLE_IS_BIO_EDIT",
	MADE_CHANGES: "MADE_CHANGES",
};
