export const ACTION_TYPES = {
	SET_NAME: "SET_NAME",
	SET_PROFILE_IMAGE_PATH: "SET_PROFILE_IMAGE_PATH",
	SET_COVER_IMAGE_PATH: "SET_COVER_IMAGE_PATH",
	SET_BIO: "SET_BIO",
	FETCH_DATA: "FETCH_DATA",
	SET_LOADING: "SET_LOADING",
	SET_IS_USER: "SET_IS_USER",
	SET_IS_FRIEND: "SET_IS_FRIEND",
	SET_LOAD_FRIEND_STATUS: "SET_LOAD_FRIEND_STATUS",
	SET_FRIEND_STATUS: "SET_FRIEND_STATUS",
	SET_FRIEND_STATUS_AND_REQUEST: "SET_FRIEND_STATUS_AND_REQUEST",
	TOGGLE_SHOW_RESPOND_FORM: "TOGGLE_SHOW_RESPOND_FORM",
};
