export const ACTION_TYPES = {
	SET_NAME: "SET_NAME",
	SET_PROFILE_IMAGE_PATH: "SET_PROFILE_IMAGE_PATH",
	SET_COVER_IMAGE_PATH: "SET_COVER_IMAGE_PATH",
	SET_BIO: "SET_BIO",
	FETCH_DATA: "FETCH_DATA",
	SET_LOADING: "SET_LOADING",
};
