const ACTION_TYPES = {
	FIRST_RENDER: "FIRST_RENDER",
	TOGGLE_SHOW_OPTION_DIV: "TOGGLE_SHOW_OPTION_DIV",
	SET_IS_PROCESSING: "SET_IS_PROCESSING",
	UP_POST: "UP_POST",
	UP_POST_AND_CANCEL_DOWN: "UP_POST_AND_CANCEL_DOWN",
	CANCEL_UP: "CANCEL_UP",
	DOWN_POST: "DOWN_POST",
	DOWN_POST_AND_CANCEL_UP: "DOWN_POST_AND_CANCEL_UP",
	CANCEL_DOWN: "CANCEL_DOWN",
	TOGGLE_VIEW_LOCATION: "TOGGLE_VIEW_LOCATION",
	TOGGLE_SHOW_EDIT_CONDITION_FORM: "TOGGLE_SHOW_EDIT_CONDITION_FORM",
	TOGGLE_SHOW_REPORT_CONDITION_FORM: "TOGGLE_SHOW_REPORT_CONDITION_FORM",
	SET_LOADING: "SET_LOADING",
	TOGGLE_CONDITION_RESOLVED: "TOGGLE_CONDITION_RESOLVED",
	FINISH_MARKING: "FINISH_MARKING",
};

export default ACTION_TYPES;
