const ACTION_TYPES = {
	FIRST_RENDER: "FIRST_RENDER",
	SET_CONDITION_TITLE: "SET_CONDITION_TITLE",
	SET_CONDITION_DESCRIPTION: "SET_CONDITION_DESCRIPTION",
	UPLOAD_IMAGE: "UPLOAD_IMAGE",
	REMOVE_IMAGE: "REMOVE_IMAGE",
	SET_LOADING: "SET_LOADING",
};

export default ACTION_TYPES;
