const ACTION_TYPES = {
	SET_EMAIL: "SET_EMAIL",
	SET_PASSWORD: "SET_PASSWORD",
	USER_NOT_EXIST: "USER_NOT_EXIST",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	SUCCESS_LOGIN: "SUCCESS_LOGIN",
	TOGGLE_VIEW_PASSWORD: "TOGGLE_VIEW_PASSWORD",
};

export default ACTION_TYPES;
