export const ACTION_TYPES = {
	SET_NAME: "SET_NAME",
	SET_GENDER: "SET_GENDER",
	SET_EMAIL: "SET_EMAIL",
	SET_PHONE_NUMBER: "SET_PHONE_NUMBER",
	SET_PASSWORD: "SET_PASSWORD",
	TOGGLE_PASSWORD: "TOGGLE_PASSWORD",
	SET_LOADING: "SET_LOADING",
	INVALID_PHONE_NUMBER: "INVALID_PHONE_NUMBER",
	INVALID_EMAIL: "INVALID_EMAIL",
	EMAIL_EXISTED: "EMAIL_EXISTED",
	PHONE_NUMBER_EXISTED: "PHONE_NUMBER_EXISTED",
	SUGGESS_REGISTER: "SUGGESS_REGISTER",
};
